name: growcarrot
description: A Flutter carrot farming guide app with multi-language support and TTS.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: any
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1   # <-- added here

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/carrot-logo-png.png"  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
